version: '3.8'

services:
  db:
    image: postgres:13
      
    volumes:
      - ./database/postgresql.conf:/etc/postgresql.conf
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
      

  app:
    build: ./backend
    ports:
      - "6001:6001"
    environment:
      DATABASE_URL: postgresql://todoapp:secret@db/tododb
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - app

volumes:
  postgres_data:

