version: '3.8'

services:
  base_de_datos:
    image: postgres:13
    volumes:
      - ./database/postgresql.conf:/etc/postgresql.conf
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - POSTGRES_USER=todoapp
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tododb
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432

  backend:
    build: ./backend
    ports:
      - 6001:6001
    environment:
      - DATABASE_URL=postgres://todoapp:secret@base_de_datos/tododb?charset=UTF8
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - base_de_datos

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:6001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
