
version: '3.8'

services:
  base_de_datos:
    image: postgres:13
    volumes:
      - ./database/postgresql.conf:/etc/postgresql.conf
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql 
    env_file: ./database/.env
    ports:
      - 5432:5432

  backend:
    image: catherinespejo/backend-todo-list:latest
    env_file: ./backend/.env
    ports:
      - 6001:6001
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - base_de_datos

  # backend-rust:
  #   env_file: ./backend-rust/.env
  #   build:
  #     context: ./backend-rust
  #     args:
  #       DATABASE_URL: ${DATABASE_URL}
  #   ports:
  #     - '6001:6001'
  #   depends_on:
  #     - base_de_datos

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file: ./frontend/.env
    depends_on:
      - backend
      #- backend-rust
